resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/dbeauregard/cf-workshop-spring-boot
    branch: concourse
- name: cloudfoundry
  type: cf
  source:
    api: {{cf-api}}
    skip_cert_check: true
    organization: {{cf-organization}}
    username: {{cf-username}}
    password: {{cf-password}}
    space: {{cf-space}}

jobs:
- name: maven-package
  plan:
  - get: git-repo
    trigger: true
  - task: maven-package
    file: git-repo/concourse/maven-package.yml
  - put: cloudfoundry
    params:
      - manifest: git-repo/manifest.yml
      - path: artifacts/boot-app.jar